-- Faeta Concept Salon Supabase reset.
-- Run this once in Supabase SQL Editor to delete old data and start clean.

drop table if exists bookings cascade;
drop table if exists clients cascade;
drop table if exists blocked_slots cascade;
drop table if exists hairstylist_availability cascade;
drop table if exists holidays cascade;
drop table if exists shop_hours cascade;
drop table if exists hairstylists cascade;
drop table if exists services cascade;
drop table if exists admin_users cascade;

create table admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  name text not null,
  display_name text not null default 'Manager',
  shop_address text not null default 'Via Cupa Fosso Del Lupo 136 NA',
  shop_name text not null default 'Faeta Concept Salon'
);

create table services (
  id bigint generated by default as identity primary key,
  name text not null,
  duration_minutes integer not null default 30,
  price numeric not null default 0,
  active boolean not null default true
);

create table hairstylists (
  id bigint generated by default as identity primary key,
  name text not null,
  specialization text not null default '',
  avatar text not null default '',
  active boolean not null default true
);

create table shop_hours (
  id bigint generated by default as identity primary key,
  day_of_week integer not null,
  open_time text,
  close_time text,
  is_closed boolean not null default false,
  lunch_start text,
  lunch_end text
);

create table holidays (
  id bigint generated by default as identity primary key,
  date text not null unique,
  name text not null default 'Festività'
);

create table hairstylist_availability (
  id bigint generated by default as identity primary key,
  hairstylist_id bigint not null references hairstylists(id) on delete cascade,
  day_of_week integer not null,
  start_time text,
  end_time text,
  is_available boolean not null default true
);

create table blocked_slots (
  id bigint generated by default as identity primary key,
  hairstylist_id bigint references hairstylists(id) on delete cascade,
  date text not null,
  start_time text,
  end_time text,
  reason text
);

create table clients (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  phone text not null,
  email text,
  notes text,
  created_at bigint not null,
  total_bookings integer not null default 0
);

create table bookings (
  id bigint generated by default as identity primary key,
  booking_code text not null unique,
  first_name text not null,
  last_name text not null,
  phone text not null default '',
  client_id bigint references clients(id) on delete set null,
  service_id bigint not null references services(id),
  hairstylist_id bigint not null references hairstylists(id),
  date text not null,
  time text not null,
  status text not null default 'confirmed',
  notes text,
  created_at bigint not null,
  is_new boolean not null default true
);

create index idx_bookings_date on bookings(date);
create index idx_bookings_hairstylist_date on bookings(hairstylist_id, date);
create index idx_clients_phone on clients(phone);
create index idx_clients_email on clients(email);

insert into admin_users (username, password_hash, name, display_name, shop_address, shop_name)
values (
  'admin',
  '$2b$10$V8BJAZG/B/wPF257GjhP.OImW.Js53Z0rfItzWc4KOattfa.9bTxy',
  'Manager',
  'Manager',
  'Via Cupa Fosso Del Lupo 136 NA',
  'Faeta Concept Salon'
);

insert into shop_hours (day_of_week, open_time, close_time, is_closed, lunch_start, lunch_end)
values
  (0, null, null, true, null, null),
  (1, null, null, true, null, null),
  (2, '08:30', '20:00', false, null, null),
  (3, '08:30', '20:00', false, null, null),
  (4, '08:30', '20:00', false, null, null),
  (5, '08:30', '20:00', false, null, null),
  (6, '08:30', '20:00', false, null, null);
